name: Publish Extension

on:
  push:
    tags:
      - "vscode-v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: vsce
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: src/vsstubs-vscode/package-lock.json

      - name: Install Dependencies
        working-directory: src/vsstubs-vscode
        run: npm install

      - name: Publish to Marketplace
        working-directory: src/vsstubs-vscode
        run: npx @vscode/vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
