name: Test Extension

on:
  push:
    branches:
      - master
    paths:
      - src/vsstubs-vscode/**
      - .github/workflows/vscode-test.yml
  pull_request:
    paths:
      - src/vsstubs-vscode/**
      - .github/workflows/vscode-test.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: voidzero-dev/setup-vp@24d870228786dc83ae73482406bdd1e7befaec14 # v1.21.0
        with:
          node-version: "24"
          working-directory: src/vsstubs-vscode
          cache: true

      - name: Test
        working-directory: src/vsstubs-vscode
        run: vpr test:coverage
