name: Publish Extension

on:
  push:
    tags:
      - "vscode-v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: vsce
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: voidzero-dev/setup-vp@49c3e4e92c52e7f8392712a9267bbe71c5ab30e5  # v1.19.0
        with:
          node-version: '24'
          cache: true

      - name: Install Dependencies
        working-directory: src/vsstubs-vscode
        run: vp install

      - name: Publish to Marketplace
        working-directory: src/vsstubs-vscode
        run: vp dlx @vscode/vsce publish --no-dependencies --no-prepublish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
